version: '3'
services:
  reveal-md:
    build: .
    image: axesor/slides_sre:latest
    volumes:
      - ./slides.md:/app/slides.md
      - ./custom.css:/app/custom.css
      - ./images:/app/images
      - ./theme/black.css:/app/theme/black.css
    ports:
      - "1948:1948"
    